Feature/add header
techmmunity/tech-frontend pull request #2
Opened 2021-02-08 15:38 UTC by alessandrohenriqueramos

2021-02-08 17:18 UTC, henriqueleite42 requested changes

2021-02-08 17:18 UTC, henriqueleite42 commented on src/components/Header/index.tsx
> +					<Login>
Usar uma div para o componente Login, assim não é necessário duplicar os elementos

2021-02-08 17:18 UTC, henriqueleite42 commented on src/components/Header/styles.ts
> +export const Container = styled.header`
Usar um `nav` ao invez de um `header`

2021-02-08 17:18 UTC, henriqueleite42 commented on src/components/Header/styles.ts
> +import styled from "styled-components";
Alterar nome da pasta pra `SideBar`

2021-02-08 17:18 UTC, henriqueleite42 commented on src/components/Header/index.tsx
> +const Header: React.FC = () => {
Alterar nome do componente pra `SideBar`

2021-02-08 17:18 UTC, henriqueleite42 commented on src/components/Header/styles.ts
> +	background: #202225;
Criar uma pasta `src/assets`, e um carquivo `colors.ts` dentro dela. Lá, colar isso:

```ts
export const Colors = {
   darkGray: "#202225"
}
```

E usar essa constante para determinar a cor da side bar

2021-02-08 17:18 UTC, henriqueleite42 commented on src/components/Header/styles.ts
> +	> nav {
Como o componente nav será apagado, juntar esse estilo com o estilo de cima.

2021-02-08 17:18 UTC, henriqueleite42 commented on src/components/Header/styles.ts
> +export const Title = styled.h1`
Não usar `<h1>`, usar `<p>`.

2021-02-08 17:18 UTC, henriqueleite42 commented on src/components/Header/styles.ts
> +	color: #43e8d8;
Usar a constante `Colors` criada anteriormente.

2021-02-08 17:18 UTC, henriqueleite42 commented on src/components/Header/styles.ts
> +		> li {
Separar esses estilos no componente que será criado.

**DICA:** Evitar ao maximo usar "elementos filhos" em styled componentes, sempre criar uma nova constante com os estilos do elemento.

2021-02-08 17:18 UTC, henriqueleite42 commented on src/components/Header/styles.ts
> +				color: #ffffff60;
Usar a constante `Colors` criada anteriormente.

2021-02-08 17:18 UTC, henriqueleite42 commented on src/components/Header/styles.ts
> +			> a {
Adicionar um hover (e mais 2 triggers que eu n lembro o nome kkkk), pra que quando passe o mouse em cima / selecione com o Tab, o texto fique com uma linha em baixo.

2021-02-08 17:18 UTC, henriqueleite42 commented on src/components/Header/styles.ts
> +		color: #fff;
Usar a constante `Colors` criada anteriormente.

2021-02-08 17:18 UTC, henriqueleite42 commented on src/styles/GlobalStyle.ts
> +
Remover esse espaço

2021-02-08 17:18 UTC, henriqueleite42 commented on src/styles/GlobalStyle.ts
> +  @media(max-width: 768px) {
Deletar esses `@media` e fazer [como nesse video](https://www.youtube.com/watch?v=H91DhKPjhPk)

2021-02-08 17:18 UTC, henriqueleite42 commented on src/styles/pages/Home.ts
> +export const Container = styled.main``;
Se não é usado, excluir.

2021-02-08 17:18 UTC, henriqueleite42 commented on src/pages/index.tsx
> +const Home: React.FC = () => {
Se não for usado, excluir.

2021-02-08 17:18 UTC, henriqueleite42 commented on src/pages/index.tsx
>  export default Home;
O export default é obrigatório do Next? Sem isso ele não reconhece os componentes? Se não for, usar `export const`.

2021-02-08 17:18 UTC, henriqueleite42 commented on src/pages/_document.tsx
> +			<Html lang="pt-br">
Trocar para `en-us`

2021-02-08 17:18 UTC, henriqueleite42 commented on src/components/Header/index.tsx
> +export default Header;
Não se deve usar export `default`, a não ser em casos obrigatórios, e mesmo nesses casos, é possivel evitar, mas faremos isso depois.

2021-02-10 00:28 UTC, alessandrohenriqueramos commented on src/components/Header/index.tsx
> +		<Container>
O elemento <header> é usado para identificar o conteúdo que precede o conteúdo principal da página da web e geralmente contém a marca do site, elementos de navegação, formulários de pesquisa e conteúdo semelhante que é duplicado em todas ou na maioria das páginas de um site e portanto é NECESSÁRIO assim como minha <div>.

2021-02-10 21:43 UTC, henriqueleite42 requested changes
Aproveitar e alterar o nome do PR pra "Add Side Bar"

2021-02-10 21:43 UTC, henriqueleite42 commented on src/assets/colors.ts
> +export const colors = {
Variaveis desse estilo devem ser definidas ou em UPPERCASE ou em PascalCase (de preferencia Pascal)

2021-02-10 21:43 UTC, henriqueleite42 commented on src/components/SideBar/Item/index.tsx
> +export default Item;
Não usar export default onde não for obrigatório.

2021-02-10 21:43 UTC, henriqueleite42 commented on src/components/SideBar/Item/styles.ts
> +import { colors } from "../../../assets/colors";
Usar absolute path

2021-02-10 21:43 UTC, henriqueleite42 commented on src/components/SideBar/index.tsx
> +					<Item url="#" comingSoon={true}>
Quando vc passa apenas a propriedade, ela já é entendida como `true`, então substituir `<Item url="#" comingSoon={true}>` por `<Item url="#" comingSoon>`

2021-02-10 21:43 UTC, henriqueleite42 commented on src/components/SideBar/styles.ts
> +import { colors } from "../../assets/colors";
User absolute path.

2021-02-10 21:43 UTC, henriqueleite42 commented on src/components/SideBar/index.tsx
> +export default SideBar;
Não usar export default onde não for obrigatório.

2021-02-10 21:43 UTC, henriqueleite42 commented on src/components/SideBar/styles.ts
> +	width: 30rem;
Adicionar `height: 100vh`, `min-height: 100vh` e `max-height: 100vh`

2021-02-10 21:43 UTC, henriqueleite42 commented on src/components/SideBar/styles.ts
> +	padding: 2rem 0;
Sem padding nos itens, apenas no container

2021-02-10 21:43 UTC, henriqueleite42 commented on src/components/SideBar/styles.ts
> +	padding: 2.5rem 0;
Usar `margin` aqui.

2021-02-10 21:43 UTC, henriqueleite42 commented on src/components/SideBar/styles.ts
> +	padding: 2.2rem 0;
Sem pading nos items, apenas no container.

2021-02-10 21:43 UTC, henriqueleite42 commented on src/components/SideBar/styles.ts
> +		&:hover {
Sempre que o estado `hover` for usado, deve-se usar tbm `active` e `focus`

2021-02-10 21:43 UTC, henriqueleite42 commented on src/pages/_app.tsx
> +import SideBar from "../components/SideBar/index";
Usar absolute path.

2021-02-10 21:43 UTC, henriqueleite42 commented on src/pages/_app.tsx
> +import GlobalStyle from "../styles/GlobalStyle";
Usar absolute path.

2021-02-12 09:37 UTC, henriqueleite42 requested changes
Fazer as alterações pedidas nois **DOIS** comentários.

2021-02-12 09:37 UTC, henriqueleite42 commented on src/components/SideBar/Item/styles.ts
> +		font-size: 2rem;
Adicionar `on hover` (e os outros 2 eventos) pra que quando o usuário passe o mouse por cima do texto, ele fique branco.

2021-02-12 11:19 UTC, henriqueleite42 approved these changes

2021-02-12 11:20 UTC, merged